services:
- type: web
  name: BeWell-backend
  env: python
  buildCommand: |
    pip install --no-cache-dir --upgrade pip setuptools wheel
    pip install --no-cache-dir -r requirements.txt
    python prepare_FAISS_vectorstore.py
  startCommand: |
    gunicorn app:app --workers 1 --threads 1 --bind 0.0.0.0:$PORT --max-requests 50 --max-requests-jitter 10 --timeout 300 --worker-class sync --worker-tmp-dir /dev/shm --preload --worker-connections 100